version: '2.1'

volumes:
    geoserver-data:
    geo-db-data:

services:
    db:
      image: kartoza/postgis:11.5-2.5
      volumes:
        - geo-db-data:/var/lib/postgresql
      expose:
        - "5432"
      env_file:
        - docker-env/db.env
      restart: on-failure
      mem_limit: 128m
      healthcheck:
        test: "exit 0"

    geoserver:
      image: adclark/focgeo:geoserver.2.16.2
      volumes:
        - geoserver-data:/opt/geoserver/data_dir
      ports:
        - "9000:8080"
        - "9443:8443"
      mem_limit: 384m
      mem_reservation: 256m
      restart: on-failure
      env_file:
        - docker-env/geoserver.env
      links:
        - "db"
      depends_on:
        db:
          condition: service_healthy
      healthcheck:
        test: curl --fail -s http://localhost:8080/geoserver || exit 1
        interval: 1m30s
        timeout: 10s
        retries: 3
